name: Update ETF SMA

on:
  schedule:
    - cron: "30 18 * * 1-5"
  workflow_dispatch:

jobs:
  update:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install -r requirements.txt

      - run: python update.py
        env:
          EOD_API_KEY: ${{ secrets.EOD_API_KEY }}

      - name: Save results
        run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git add data results.csv
          git commit -m "Update ETF data" || exit 0
          git push
